packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - sharp
  - unrs-resolver

overrides:
  diff@<8.0.3: ">=8.0.3"
  glob@>=10.2.0 <10.5.0: ">=10.5.0"
  qs@<6.14.1: ">=6.14.1"
  tmp@<=0.2.3: ">=0.2.4"
